/*!
**  Author:   James Dolan (jdolan@gmail.com)
**
**  Notes:    OpenGL MultiTexture extensions.
*/


#include "OpenGLMultText.h"
#ifdef LV_APPLE
#include "aglGetProcAddress.h"
#endif

PFNGLMULTITEXCOORD1DARBPROC     glMultiTexCoord1dARB        = 0;
PFNGLMULTITEXCOORD1DVARBPROC    glMultiTexCoord1dvARB       = 0;
PFNGLMULTITEXCOORD1FARBPROC     glMultiTexCoord1fARB        = 0;
PFNGLMULTITEXCOORD1FVARBPROC    glMultiTexCoord1fvARB       = 0;
PFNGLMULTITEXCOORD1IARBPROC     glMultiTexCoord1iARB        = 0;
PFNGLMULTITEXCOORD1IVARBPROC    glMultiTexCoord1ivARB       = 0;
PFNGLMULTITEXCOORD1SARBPROC     glMultiTexCoord1sARB        = 0;
PFNGLMULTITEXCOORD1SVARBPROC    glMultiTexCoord1svARB       = 0;
PFNGLMULTITEXCOORD2DARBPROC     glMultiTexCoord2dARB        = 0;
PFNGLMULTITEXCOORD2DVARBPROC    glMultiTexCoord2dvARB       = 0;
PFNGLMULTITEXCOORD2FARBPROC     glMultiTexCoord2fARB        = 0;
PFNGLMULTITEXCOORD2FVARBPROC    glMultiTexCoord2fvARB       = 0;
PFNGLMULTITEXCOORD2IARBPROC     glMultiTexCoord2iARB        = 0;
PFNGLMULTITEXCOORD2IVARBPROC    glMultiTexCoord2ivARB       = 0;
PFNGLMULTITEXCOORD2SARBPROC     glMultiTexCoord2sARB        = 0;
PFNGLMULTITEXCOORD2SVARBPROC    glMultiTexCoord2svARB       = 0;
PFNGLMULTITEXCOORD3DARBPROC     glMultiTexCoord3dARB        = 0;
PFNGLMULTITEXCOORD3DVARBPROC    glMultiTexCoord3dvARB       = 0;
PFNGLMULTITEXCOORD3FARBPROC     glMultiTexCoord3fARB        = 0;
PFNGLMULTITEXCOORD3FVARBPROC    glMultiTexCoord3fvARB       = 0;
PFNGLMULTITEXCOORD3IARBPROC     glMultiTexCoord3iARB        = 0;
PFNGLMULTITEXCOORD3IVARBPROC    glMultiTexCoord3ivARB       = 0;
PFNGLMULTITEXCOORD3SARBPROC     glMultiTexCoord3sARB        = 0;
PFNGLMULTITEXCOORD3SVARBPROC    glMultiTexCoord3svARB       = 0;
PFNGLMULTITEXCOORD4DARBPROC     glMultiTexCoord4dARB        = 0;
PFNGLMULTITEXCOORD4DVARBPROC    glMultiTexCoord4dvARB       = 0;
PFNGLMULTITEXCOORD4FARBPROC     glMultiTexCoord4fARB        = 0;
PFNGLMULTITEXCOORD4FVARBPROC    glMultiTexCoord4fvARB       = 0;
PFNGLMULTITEXCOORD4IARBPROC     glMultiTexCoord4iARB        = 0;
PFNGLMULTITEXCOORD4IVARBPROC    glMultiTexCoord4ivARB       = 0;
PFNGLMULTITEXCOORD4SARBPROC     glMultiTexCoord4sdARB       = 0;
PFNGLMULTITEXCOORD4SVARBPROC    glMultiTexCoord4svARB       = 0;
PFNGLACTIVETEXTUREARBPROC       glActiveTextureARB          = 0;
PFNGLCLIENTACTIVETEXTUREARBPROC glClientActiveTextureARB    = 0;

#ifdef LV_WINDOWS
#define LV_LOADGLEXT(_Type, _Name) (((_Name = (_Type) wglGetProcAddress(#_Name)) == 0) ? LV_BAD_OUTPUT : error)
#endif

#ifdef LV_APPLE
#define LV_LOADGLEXT(_Type, _Name) (((_Name = (_Type) aglGetProcAddress(#_Name)) == 0) ? LV_BAD_OUTPUT : error)
#endif

/*!
**  Notes:    Load the extensions.
**/
LvError glextLoadMultText(void)
{
  LvError error = LV_OKAY;
  
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD1DARBPROC,    glMultiTexCoord1dARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD1DVARBPROC,   glMultiTexCoord1dvARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD1FARBPROC,    glMultiTexCoord1fARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD1FVARBPROC,   glMultiTexCoord1fvARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD1IARBPROC,    glMultiTexCoord1iARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD1IVARBPROC,   glMultiTexCoord1ivARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD1SARBPROC,    glMultiTexCoord1sARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD1SVARBPROC,   glMultiTexCoord1svARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD2DARBPROC,    glMultiTexCoord2dARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD2DVARBPROC,   glMultiTexCoord2dvARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD2FARBPROC,    glMultiTexCoord2fARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD2FVARBPROC,   glMultiTexCoord2fvARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD2IARBPROC,    glMultiTexCoord2iARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD2IVARBPROC,   glMultiTexCoord2ivARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD2SARBPROC,    glMultiTexCoord2sARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD2SVARBPROC,   glMultiTexCoord2svARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD3DARBPROC,    glMultiTexCoord3dARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD3DVARBPROC,   glMultiTexCoord3dvARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD3FARBPROC,    glMultiTexCoord3fARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD3FVARBPROC,   glMultiTexCoord3fvARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD3IARBPROC,    glMultiTexCoord3iARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD3IVARBPROC,   glMultiTexCoord3ivARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD3SARBPROC,    glMultiTexCoord3sARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD3SVARBPROC,   glMultiTexCoord3svARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD4DARBPROC,    glMultiTexCoord4dARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD4DVARBPROC,   glMultiTexCoord4dvARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD4FARBPROC,    glMultiTexCoord4fARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD4FVARBPROC,   glMultiTexCoord4fvARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD4IARBPROC,    glMultiTexCoord4iARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD4IVARBPROC,   glMultiTexCoord4ivARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD4SARBPROC,    glMultiTexCoord4sdARB);
  error = LV_LOADGLEXT(PFNGLMULTITEXCOORD4SVARBPROC,   glMultiTexCoord4svARB);
  error = LV_LOADGLEXT(PFNGLACTIVETEXTUREARBPROC,      glActiveTextureARB);
  error = LV_LOADGLEXT(PFNGLCLIENTACTIVETEXTUREARBPROC,glClientActiveTextureARB);
  
  return error;
}
